//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 03:50:15 PM CDT 
//


package com.opencfdimovil.sat.cfdi.v32.schema;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Percepciones" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Percepcion" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="TipoPercepcion" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;pattern value="[0-9]{3}"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="Clave" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="3"/>
 *                                 &lt;maxLength value="15"/>
 *                                 &lt;whiteSpace value="collapse"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="Concepto" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="1"/>
 *                                 &lt;maxLength value="100"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="ImporteGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                           &lt;attribute name="ImporteExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="TotalGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                 &lt;attribute name="TotalExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Deducciones" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Deduccion" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="TipoDeduccion" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;pattern value="[0-9]{3}"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="Clave" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="3"/>
 *                                 &lt;maxLength value="15"/>
 *                                 &lt;whiteSpace value="collapse"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="Concepto" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="1"/>
 *                                 &lt;maxLength value="100"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="ImporteGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                           &lt;attribute name="ImporteExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="TotalGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                 &lt;attribute name="TotalExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Incapacidades" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Incapacidad" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="DiasIncapacidad" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                 &lt;fractionDigits value="6"/>
 *                                 &lt;minInclusive value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="TipoIncapacidad" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Descuento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="HorasExtras" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="HorasExtra" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Dias" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="TipoHoras" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;whiteSpace value="collapse"/>
 *                                 &lt;enumeration value="Dobles"/>
 *                                 &lt;enumeration value="Triples"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="HorasExtra" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="ImportePagado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.1" />
 *       &lt;attribute name="RegistroPatronal">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="20"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NumEmpleado" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="15"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CURP" use="required" type="{http://www.sat.gob.mx/nomina}t_CURP" />
 *       &lt;attribute name="TipoRegimen" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NumSeguridadSocial">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="15"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="FechaPago" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="FechaInicialPago" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="FechaFinalPago" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="NumDiasPagados" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;fractionDigits value="6"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Departamento">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="100"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CLABE" type="{http://www.sat.gob.mx/nomina}t_Clabe" />
 *       &lt;attribute name="Banco">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9]{3}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="FechaInicioRelLaboral" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="Antiguedad" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Puesto" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TipoContrato" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TipoJornada" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PeriodicidadPago" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="100"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SalarioBaseCotApor" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *       &lt;attribute name="RiesgoPuesto">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SalarioDiarioIntegrado" type="{http://www.sat.gob.mx/nomina}t_Importe" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class Nomina
    implements Serializable
{

    private final static long serialVersionUID = -6026937020915831338L;
    protected Nomina.Percepciones percepciones;
    protected Nomina.Deducciones deducciones;
    protected Nomina.Incapacidades incapacidades;
    protected Nomina.HorasExtras horasExtras;
    protected String version;
    protected String registroPatronal;
    protected String numEmpleado;
    protected NCURP curp;
    protected int tipoRegimen;
    protected String numSeguridadSocial;
    protected Date fechaPago;
    protected Date fechaInicialPago;
    protected Date fechaFinalPago;
    protected BigDecimal numDiasPagados;
    protected String departamento;
    protected BigInteger clabe;
    protected String banco;
    protected Date fechaInicioRelLaboral;
    protected Integer antiguedad;
    protected String puesto;
    protected String tipoContrato;
    protected String tipoJornada;
    protected String periodicidadPago;
    protected NImporte salarioBaseCotApor;
    protected Integer riesgoPuesto;
    protected NImporte salarioDiarioIntegrado;

    /**
     * Gets the value of the percepciones property.
     * 
     * @return
     *     possible object is
     *     {@link Nomina.Percepciones }
     *     
     */
    public Nomina.Percepciones getPercepciones() {
        return percepciones;
    }

    /**
     * Sets the value of the percepciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nomina.Percepciones }
     *     
     */
    public void setPercepciones(Nomina.Percepciones value) {
        this.percepciones = value;
    }

    /**
     * Gets the value of the deducciones property.
     * 
     * @return
     *     possible object is
     *     {@link Nomina.Deducciones }
     *     
     */
    public Nomina.Deducciones getDeducciones() {
        return deducciones;
    }

    /**
     * Sets the value of the deducciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nomina.Deducciones }
     *     
     */
    public void setDeducciones(Nomina.Deducciones value) {
        this.deducciones = value;
    }

    /**
     * Gets the value of the incapacidades property.
     * 
     * @return
     *     possible object is
     *     {@link Nomina.Incapacidades }
     *     
     */
    public Nomina.Incapacidades getIncapacidades() {
        return incapacidades;
    }

    /**
     * Sets the value of the incapacidades property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nomina.Incapacidades }
     *     
     */
    public void setIncapacidades(Nomina.Incapacidades value) {
        this.incapacidades = value;
    }

    /**
     * Gets the value of the horasExtras property.
     * 
     * @return
     *     possible object is
     *     {@link Nomina.HorasExtras }
     *     
     */
    public Nomina.HorasExtras getHorasExtras() {
        return horasExtras;
    }

    /**
     * Sets the value of the horasExtras property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nomina.HorasExtras }
     *     
     */
    public void setHorasExtras(Nomina.HorasExtras value) {
        this.horasExtras = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.1";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the registroPatronal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistroPatronal() {
        return registroPatronal;
    }

    /**
     * Sets the value of the registroPatronal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistroPatronal(String value) {
        this.registroPatronal = value;
    }

    /**
     * Gets the value of the numEmpleado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumEmpleado() {
        return numEmpleado;
    }

    /**
     * Sets the value of the numEmpleado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumEmpleado(String value) {
        this.numEmpleado = value;
    }

    /**
     * Gets the value of the curp property.
     * 
     * @return
     *     possible object is
     *     {@link NCURP }
     *     
     */
    public NCURP getCURP() {
        return curp;
    }

    /**
     * Sets the value of the curp property.
     * 
     * @param value
     *     allowed object is
     *     {@link NCURP }
     *     
     */
    public void setCURP(NCURP value) {
        this.curp = value;
    }

    /**
     * Gets the value of the tipoRegimen property.
     * 
     */
    public int getTipoRegimen() {
        return tipoRegimen;
    }

    /**
     * Sets the value of the tipoRegimen property.
     * 
     */
    public void setTipoRegimen(int value) {
        this.tipoRegimen = value;
    }

    /**
     * Gets the value of the numSeguridadSocial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumSeguridadSocial() {
        return numSeguridadSocial;
    }

    /**
     * Sets the value of the numSeguridadSocial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumSeguridadSocial(String value) {
        this.numSeguridadSocial = value;
    }

    /**
     * Gets the value of the fechaPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getFechaPago() {
        return fechaPago;
    }

    /**
     * Sets the value of the fechaPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaPago(Date value) {
        this.fechaPago = value;
    }

    /**
     * Gets the value of the fechaInicialPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getFechaInicialPago() {
        return fechaInicialPago;
    }

    /**
     * Sets the value of the fechaInicialPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaInicialPago(Date value) {
        this.fechaInicialPago = value;
    }

    /**
     * Gets the value of the fechaFinalPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getFechaFinalPago() {
        return fechaFinalPago;
    }

    /**
     * Sets the value of the fechaFinalPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaFinalPago(Date value) {
        this.fechaFinalPago = value;
    }

    /**
     * Gets the value of the numDiasPagados property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumDiasPagados() {
        return numDiasPagados;
    }

    /**
     * Sets the value of the numDiasPagados property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumDiasPagados(BigDecimal value) {
        this.numDiasPagados = value;
    }

    /**
     * Gets the value of the departamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartamento() {
        return departamento;
    }

    /**
     * Sets the value of the departamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartamento(String value) {
        this.departamento = value;
    }

    /**
     * Gets the value of the clabe property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCLABE() {
        return clabe;
    }

    /**
     * Sets the value of the clabe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCLABE(BigInteger value) {
        this.clabe = value;
    }

    /**
     * Gets the value of the banco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBanco() {
        return banco;
    }

    /**
     * Sets the value of the banco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBanco(String value) {
        this.banco = value;
    }

    /**
     * Gets the value of the fechaInicioRelLaboral property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getFechaInicioRelLaboral() {
        return fechaInicioRelLaboral;
    }

    /**
     * Sets the value of the fechaInicioRelLaboral property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaInicioRelLaboral(Date value) {
        this.fechaInicioRelLaboral = value;
    }

    /**
     * Gets the value of the antiguedad property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAntiguedad() {
        return antiguedad;
    }

    /**
     * Sets the value of the antiguedad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAntiguedad(Integer value) {
        this.antiguedad = value;
    }

    /**
     * Gets the value of the puesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPuesto() {
        return puesto;
    }

    /**
     * Sets the value of the puesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPuesto(String value) {
        this.puesto = value;
    }

    /**
     * Gets the value of the tipoContrato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoContrato() {
        return tipoContrato;
    }

    /**
     * Sets the value of the tipoContrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoContrato(String value) {
        this.tipoContrato = value;
    }

    /**
     * Gets the value of the tipoJornada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoJornada() {
        return tipoJornada;
    }

    /**
     * Sets the value of the tipoJornada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoJornada(String value) {
        this.tipoJornada = value;
    }

    /**
     * Gets the value of the periodicidadPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodicidadPago() {
        return periodicidadPago;
    }

    /**
     * Sets the value of the periodicidadPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodicidadPago(String value) {
        this.periodicidadPago = value;
    }

    /**
     * Gets the value of the salarioBaseCotApor property.
     * 
     * @return
     *     possible object is
     *     {@link NImporte }
     *     
     */
    public NImporte getSalarioBaseCotApor() {
        return salarioBaseCotApor;
    }

    /**
     * Sets the value of the salarioBaseCotApor property.
     * 
     * @param value
     *     allowed object is
     *     {@link NImporte }
     *     
     */
    public void setSalarioBaseCotApor(NImporte value) {
        this.salarioBaseCotApor = value;
    }

    /**
     * Gets the value of the riesgoPuesto property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRiesgoPuesto() {
        return riesgoPuesto;
    }

    /**
     * Sets the value of the riesgoPuesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRiesgoPuesto(Integer value) {
        this.riesgoPuesto = value;
    }

    /**
     * Gets the value of the salarioDiarioIntegrado property.
     * 
     * @return
     *     possible object is
     *     {@link NImporte }
     *     
     */
    public NImporte getSalarioDiarioIntegrado() {
        return salarioDiarioIntegrado;
    }

    /**
     * Sets the value of the salarioDiarioIntegrado property.
     * 
     * @param value
     *     allowed object is
     *     {@link NImporte }
     *     
     */
    public void setSalarioDiarioIntegrado(NImporte value) {
        this.salarioDiarioIntegrado = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Deduccion" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="TipoDeduccion" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;pattern value="[0-9]{3}"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="Clave" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="3"/>
     *                       &lt;maxLength value="15"/>
     *                       &lt;whiteSpace value="collapse"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="Concepto" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="1"/>
     *                       &lt;maxLength value="100"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="ImporteGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *                 &lt;attribute name="ImporteExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="TotalGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *       &lt;attribute name="TotalExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public static class Deducciones
        implements Serializable
    {

        private final static long serialVersionUID = -6026937020915831338L;
        protected List<Nomina.Deducciones.Deduccion> deduccion;
        protected NImporte totalGravado;
        protected NImporte totalExento;

        /**
         * Gets the value of the deduccion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the deduccion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDeduccion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Nomina.Deducciones.Deduccion }
         * 
         * 
         */
        public List<Nomina.Deducciones.Deduccion> getDeduccion() {
            if (deduccion == null) {
                deduccion = new ArrayList<Nomina.Deducciones.Deduccion>();
            }
            return this.deduccion;
        }

        /**
         * Gets the value of the totalGravado property.
         * 
         * @return
         *     possible object is
         *     {@link NImporte }
         *     
         */
        public NImporte getTotalGravado() {
            return totalGravado;
        }

        /**
         * Sets the value of the totalGravado property.
         * 
         * @param value
         *     allowed object is
         *     {@link NImporte }
         *     
         */
        public void setTotalGravado(NImporte value) {
            this.totalGravado = value;
        }

        /**
         * Gets the value of the totalExento property.
         * 
         * @return
         *     possible object is
         *     {@link NImporte }
         *     
         */
        public NImporte getTotalExento() {
            return totalExento;
        }

        /**
         * Sets the value of the totalExento property.
         * 
         * @param value
         *     allowed object is
         *     {@link NImporte }
         *     
         */
        public void setTotalExento(NImporte value) {
            this.totalExento = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="TipoDeduccion" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;pattern value="[0-9]{3}"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="Clave" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="3"/>
         *             &lt;maxLength value="15"/>
         *             &lt;whiteSpace value="collapse"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="Concepto" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="1"/>
         *             &lt;maxLength value="100"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="ImporteGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
         *       &lt;attribute name="ImporteExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        public static class Deduccion
            implements Serializable
        {

            private final static long serialVersionUID = -6026937020915831338L;
            protected String tipoDeduccion;
            protected String clave;
            protected String concepto;
            protected NImporte importeGravado;
            protected NImporte importeExento;

            /**
             * Gets the value of the tipoDeduccion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipoDeduccion() {
                return tipoDeduccion;
            }

            /**
             * Sets the value of the tipoDeduccion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipoDeduccion(String value) {
                this.tipoDeduccion = value;
            }

            /**
             * Gets the value of the clave property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClave() {
                return clave;
            }

            /**
             * Sets the value of the clave property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClave(String value) {
                this.clave = value;
            }

            /**
             * Gets the value of the concepto property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getConcepto() {
                return concepto;
            }

            /**
             * Sets the value of the concepto property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setConcepto(String value) {
                this.concepto = value;
            }

            /**
             * Gets the value of the importeGravado property.
             * 
             * @return
             *     possible object is
             *     {@link NImporte }
             *     
             */
            public NImporte getImporteGravado() {
                return importeGravado;
            }

            /**
             * Sets the value of the importeGravado property.
             * 
             * @param value
             *     allowed object is
             *     {@link NImporte }
             *     
             */
            public void setImporteGravado(NImporte value) {
                this.importeGravado = value;
            }

            /**
             * Gets the value of the importeExento property.
             * 
             * @return
             *     possible object is
             *     {@link NImporte }
             *     
             */
            public NImporte getImporteExento() {
                return importeExento;
            }

            /**
             * Sets the value of the importeExento property.
             * 
             * @param value
             *     allowed object is
             *     {@link NImporte }
             *     
             */
            public void setImporteExento(NImporte value) {
                this.importeExento = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="HorasExtra" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="Dias" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="TipoHoras" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;whiteSpace value="collapse"/>
     *                       &lt;enumeration value="Dobles"/>
     *                       &lt;enumeration value="Triples"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="HorasExtra" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="ImportePagado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public static class HorasExtras
        implements Serializable
    {

        private final static long serialVersionUID = -6026937020915831338L;
        protected List<Nomina.HorasExtras.HorasExtra> horasExtra;

        /**
         * Gets the value of the horasExtra property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the horasExtra property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHorasExtra().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Nomina.HorasExtras.HorasExtra }
         * 
         * 
         */
        public List<Nomina.HorasExtras.HorasExtra> getHorasExtra() {
            if (horasExtra == null) {
                horasExtra = new ArrayList<Nomina.HorasExtras.HorasExtra>();
            }
            return this.horasExtra;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="Dias" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="TipoHoras" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;whiteSpace value="collapse"/>
         *             &lt;enumeration value="Dobles"/>
         *             &lt;enumeration value="Triples"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="HorasExtra" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="ImportePagado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        public static class HorasExtra
            implements Serializable
        {

            private final static long serialVersionUID = -6026937020915831338L;
            protected int dias;
            protected String tipoHoras;
            protected int horasExtra;
            protected NImporte importePagado;

            /**
             * Gets the value of the dias property.
             * 
             */
            public int getDias() {
                return dias;
            }

            /**
             * Sets the value of the dias property.
             * 
             */
            public void setDias(int value) {
                this.dias = value;
            }

            /**
             * Gets the value of the tipoHoras property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipoHoras() {
                return tipoHoras;
            }

            /**
             * Sets the value of the tipoHoras property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipoHoras(String value) {
                this.tipoHoras = value;
            }

            /**
             * Gets the value of the horasExtra property.
             * 
             */
            public int getHorasExtra() {
                return horasExtra;
            }

            /**
             * Sets the value of the horasExtra property.
             * 
             */
            public void setHorasExtra(int value) {
                this.horasExtra = value;
            }

            /**
             * Gets the value of the importePagado property.
             * 
             * @return
             *     possible object is
             *     {@link NImporte }
             *     
             */
            public NImporte getImportePagado() {
                return importePagado;
            }

            /**
             * Sets the value of the importePagado property.
             * 
             * @param value
             *     allowed object is
             *     {@link NImporte }
             *     
             */
            public void setImportePagado(NImporte value) {
                this.importePagado = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Incapacidad" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="DiasIncapacidad" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                       &lt;fractionDigits value="6"/>
     *                       &lt;minInclusive value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="TipoIncapacidad" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="Descuento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public static class Incapacidades
        implements Serializable
    {

        private final static long serialVersionUID = -6026937020915831338L;
        protected List<Nomina.Incapacidades.Incapacidad> incapacidad;

        /**
         * Gets the value of the incapacidad property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the incapacidad property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIncapacidad().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Nomina.Incapacidades.Incapacidad }
         * 
         * 
         */
        public List<Nomina.Incapacidades.Incapacidad> getIncapacidad() {
            if (incapacidad == null) {
                incapacidad = new ArrayList<Nomina.Incapacidades.Incapacidad>();
            }
            return this.incapacidad;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="DiasIncapacidad" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *             &lt;fractionDigits value="6"/>
         *             &lt;minInclusive value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="TipoIncapacidad" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="Descuento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        public static class Incapacidad
            implements Serializable
        {

            private final static long serialVersionUID = -6026937020915831338L;
            protected BigDecimal diasIncapacidad;
            protected int tipoIncapacidad;
            protected NImporte descuento;

            /**
             * Gets the value of the diasIncapacidad property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDiasIncapacidad() {
                return diasIncapacidad;
            }

            /**
             * Sets the value of the diasIncapacidad property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDiasIncapacidad(BigDecimal value) {
                this.diasIncapacidad = value;
            }

            /**
             * Gets the value of the tipoIncapacidad property.
             * 
             */
            public int getTipoIncapacidad() {
                return tipoIncapacidad;
            }

            /**
             * Sets the value of the tipoIncapacidad property.
             * 
             */
            public void setTipoIncapacidad(int value) {
                this.tipoIncapacidad = value;
            }

            /**
             * Gets the value of the descuento property.
             * 
             * @return
             *     possible object is
             *     {@link NImporte }
             *     
             */
            public NImporte getDescuento() {
                return descuento;
            }

            /**
             * Sets the value of the descuento property.
             * 
             * @param value
             *     allowed object is
             *     {@link NImporte }
             *     
             */
            public void setDescuento(NImporte value) {
                this.descuento = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Percepcion" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="TipoPercepcion" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;pattern value="[0-9]{3}"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="Clave" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="3"/>
     *                       &lt;maxLength value="15"/>
     *                       &lt;whiteSpace value="collapse"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="Concepto" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="1"/>
     *                       &lt;maxLength value="100"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="ImporteGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *                 &lt;attribute name="ImporteExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="TotalGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *       &lt;attribute name="TotalExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public static class Percepciones
        implements Serializable
    {

        private final static long serialVersionUID = -6026937020915831338L;
        protected List<Nomina.Percepciones.Percepcion> percepcion;
        protected NImporte totalGravado;
        protected NImporte totalExento;

        /**
         * Gets the value of the percepcion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the percepcion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPercepcion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Nomina.Percepciones.Percepcion }
         * 
         * 
         */
        public List<Nomina.Percepciones.Percepcion> getPercepcion() {
            if (percepcion == null) {
                percepcion = new ArrayList<Nomina.Percepciones.Percepcion>();
            }
            return this.percepcion;
        }

        /**
         * Gets the value of the totalGravado property.
         * 
         * @return
         *     possible object is
         *     {@link NImporte }
         *     
         */
        public NImporte getTotalGravado() {
            return totalGravado;
        }

        /**
         * Sets the value of the totalGravado property.
         * 
         * @param value
         *     allowed object is
         *     {@link NImporte }
         *     
         */
        public void setTotalGravado(NImporte value) {
            this.totalGravado = value;
        }

        /**
         * Gets the value of the totalExento property.
         * 
         * @return
         *     possible object is
         *     {@link NImporte }
         *     
         */
        public NImporte getTotalExento() {
            return totalExento;
        }

        /**
         * Sets the value of the totalExento property.
         * 
         * @param value
         *     allowed object is
         *     {@link NImporte }
         *     
         */
        public void setTotalExento(NImporte value) {
            this.totalExento = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="TipoPercepcion" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;pattern value="[0-9]{3}"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="Clave" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="3"/>
         *             &lt;maxLength value="15"/>
         *             &lt;whiteSpace value="collapse"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="Concepto" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="1"/>
         *             &lt;maxLength value="100"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="ImporteGravado" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
         *       &lt;attribute name="ImporteExento" use="required" type="{http://www.sat.gob.mx/nomina}t_Importe" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        public static class Percepcion
            implements Serializable
        {

            private final static long serialVersionUID = -6026937020915831338L;
            protected String tipoPercepcion;
            protected String clave;
            protected String concepto;
            protected NImporte importeGravado;
            protected NImporte importeExento;

            /**
             * Gets the value of the tipoPercepcion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipoPercepcion() {
                return tipoPercepcion;
            }

            /**
             * Sets the value of the tipoPercepcion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipoPercepcion(String value) {
                this.tipoPercepcion = value;
            }

            /**
             * Gets the value of the clave property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClave() {
                return clave;
            }

            /**
             * Sets the value of the clave property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClave(String value) {
                this.clave = value;
            }

            /**
             * Gets the value of the concepto property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getConcepto() {
                return concepto;
            }

            /**
             * Sets the value of the concepto property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setConcepto(String value) {
                this.concepto = value;
            }

            /**
             * Gets the value of the importeGravado property.
             * 
             * @return
             *     possible object is
             *     {@link NImporte }
             *     
             */
            public NImporte getImporteGravado() {
                return importeGravado;
            }

            /**
             * Sets the value of the importeGravado property.
             * 
             * @param value
             *     allowed object is
             *     {@link NImporte }
             *     
             */
            public void setImporteGravado(NImporte value) {
                this.importeGravado = value;
            }

            /**
             * Gets the value of the importeExento property.
             * 
             * @return
             *     possible object is
             *     {@link NImporte }
             *     
             */
            public NImporte getImporteExento() {
                return importeExento;
            }

            /**
             * Sets the value of the importeExento property.
             * 
             * @param value
             *     allowed object is
             *     {@link NImporte }
             *     
             */
            public void setImporteExento(NImporte value) {
                this.importeExento = value;
            }

        }

    }

}
