//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 03:50:15 PM CDT 
//


package com.opencfdimovil.sat.cfdi.v32.schema;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.reemmy.sat.cfdi.v32.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.reemmy.sat.cfdi.v32.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Comprobante }
     * 
     */
    public Comprobante createComprobante() {
        return new Comprobante();
    }

    /**
     * Create an instance of {@link VentaVehiculos }
     * 
     */
    public VentaVehiculos createVentaVehiculos() {
        return new VentaVehiculos();
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros }
     * 
     */
    public PorCuentadeTerceros createPorCuentadeTerceros() {
        return new PorCuentadeTerceros();
    }

    /**
     * Create an instance of {@link Nomina }
     * 
     */
    public Nomina createNomina() {
        return new Nomina();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaBancario }
     * 
     */
    public EstadoDeCuentaBancario createEstadoDeCuentaBancario() {
        return new EstadoDeCuentaBancario();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaCombustible }
     * 
     */
    public EstadoDeCuentaCombustible createEstadoDeCuentaCombustible() {
        return new EstadoDeCuentaCombustible();
    }

    /**
     * Create an instance of {@link ImpuestosLocales }
     * 
     */
    public ImpuestosLocales createImpuestosLocales() {
        return new ImpuestosLocales();
    }

    /**
     * Create an instance of {@link LeyendasFiscales }
     * 
     */
    public LeyendasFiscales createLeyendasFiscales() {
        return new LeyendasFiscales();
    }

    /**
     * Create an instance of {@link TuristaPasajeroExtranjero }
     * 
     */
    public TuristaPasajeroExtranjero createTuristaPasajeroExtranjero() {
        return new TuristaPasajeroExtranjero();
    }

    /**
     * Create an instance of {@link ComplementoSPEI }
     * 
     */
    public ComplementoSPEI createComplementoSPEI() {
        return new ComplementoSPEI();
    }

    /**
     * Create an instance of {@link ComplementoSPEI.SPEITercero }
     * 
     */
    public ComplementoSPEI.SPEITercero createComplementoSPEISPEITercero() {
        return new ComplementoSPEI.SPEITercero();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaCombustible.Conceptos }
     * 
     */
    public EstadoDeCuentaCombustible.Conceptos createEstadoDeCuentaCombustibleConceptos() {
        return new EstadoDeCuentaCombustible.Conceptos();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible }
     * 
     */
    public EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible createEstadoDeCuentaCombustibleConceptosConceptoEstadoDeCuentaCombustible() {
        return new EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados }
     * 
     */
    public EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados createEstadoDeCuentaCombustibleConceptosConceptoEstadoDeCuentaCombustibleTraslados() {
        return new EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaBancario.Movimientos }
     * 
     */
    public EstadoDeCuentaBancario.Movimientos createEstadoDeCuentaBancarioMovimientos() {
        return new EstadoDeCuentaBancario.Movimientos();
    }

    /**
     * Create an instance of {@link Nomina.HorasExtras }
     * 
     */
    public Nomina.HorasExtras createNominaHorasExtras() {
        return new Nomina.HorasExtras();
    }

    /**
     * Create an instance of {@link Nomina.Incapacidades }
     * 
     */
    public Nomina.Incapacidades createNominaIncapacidades() {
        return new Nomina.Incapacidades();
    }

    /**
     * Create an instance of {@link Nomina.Deducciones }
     * 
     */
    public Nomina.Deducciones createNominaDeducciones() {
        return new Nomina.Deducciones();
    }

    /**
     * Create an instance of {@link Nomina.Percepciones }
     * 
     */
    public Nomina.Percepciones createNominaPercepciones() {
        return new Nomina.Percepciones();
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros.Impuestos }
     * 
     */
    public PorCuentadeTerceros.Impuestos createPorCuentadeTercerosImpuestos() {
        return new PorCuentadeTerceros.Impuestos();
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros.Impuestos.Traslados }
     * 
     */
    public PorCuentadeTerceros.Impuestos.Traslados createPorCuentadeTercerosImpuestosTraslados() {
        return new PorCuentadeTerceros.Impuestos.Traslados();
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros.Impuestos.Retenciones }
     * 
     */
    public PorCuentadeTerceros.Impuestos.Retenciones createPorCuentadeTercerosImpuestosRetenciones() {
        return new PorCuentadeTerceros.Impuestos.Retenciones();
    }

    /**
     * Create an instance of {@link Comprobante.Impuestos }
     * 
     */
    public Comprobante.Impuestos createComprobanteImpuestos() {
        return new Comprobante.Impuestos();
    }

    /**
     * Create an instance of {@link Comprobante.Impuestos.Traslados }
     * 
     */
    public Comprobante.Impuestos.Traslados createComprobanteImpuestosTraslados() {
        return new Comprobante.Impuestos.Traslados();
    }

    /**
     * Create an instance of {@link Comprobante.Impuestos.Retenciones }
     * 
     */
    public Comprobante.Impuestos.Retenciones createComprobanteImpuestosRetenciones() {
        return new Comprobante.Impuestos.Retenciones();
    }

    /**
     * Create an instance of {@link Comprobante.Conceptos }
     * 
     */
    public Comprobante.Conceptos createComprobanteConceptos() {
        return new Comprobante.Conceptos();
    }

    /**
     * Create an instance of {@link Comprobante.Conceptos.Concepto }
     * 
     */
    public Comprobante.Conceptos.Concepto createComprobanteConceptosConcepto() {
        return new Comprobante.Conceptos.Concepto();
    }

    /**
     * Create an instance of {@link Comprobante.Emisor }
     * 
     */
    public Comprobante.Emisor createComprobanteEmisor() {
        return new Comprobante.Emisor();
    }

    /**
     * Create an instance of {@link Comprobante.Receptor }
     * 
     */
    public Comprobante.Receptor createComprobanteReceptor() {
        return new Comprobante.Receptor();
    }

    /**
     * Create an instance of {@link Comprobante.Complemento }
     * 
     */
    public Comprobante.Complemento createComprobanteComplemento() {
        return new Comprobante.Complemento();
    }

    /**
     * Create an instance of {@link Comprobante.Addenda }
     * 
     */
    public Comprobante.Addenda createComprobanteAddenda() {
        return new Comprobante.Addenda();
    }

    /**
     * Create an instance of {@link TInformacionAduanera }
     * 
     */
    public TInformacionAduanera createTInformacionAduanera() {
        return new TInformacionAduanera();
    }

    /**
     * Create an instance of {@link TUbicacionFiscal }
     * 
     */
    public TUbicacionFiscal createTUbicacionFiscal() {
        return new TUbicacionFiscal();
    }

    /**
     * Create an instance of {@link TUbicacion }
     * 
     */
    public TUbicacion createTUbicacion() {
        return new TUbicacion();
    }

    /**
     * Create an instance of {@link TimbreFiscalDigital }
     * 
     */
    public TimbreFiscalDigital createTimbreFiscalDigital() {
        return new TimbreFiscalDigital();
    }

    /**
     * Create an instance of {@link VInformacionAduanera32 }
     * 
     */
    public VInformacionAduanera32 createVInformacionAduanera32() {
        return new VInformacionAduanera32();
    }

    /**
     * Create an instance of {@link VentaVehiculos.Parte }
     * 
     */
    public VentaVehiculos.Parte createVentaVehiculosParte() {
        return new VentaVehiculos.Parte();
    }

    /**
     * Create an instance of {@link VImporte }
     * 
     */
    public VImporte createVImporte() {
        return new VImporte();
    }

    /**
     * Create an instance of {@link InstEducativas }
     * 
     */
    public InstEducativas createInstEducativas() {
        return new InstEducativas();
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros.InformacionFiscalTercero }
     * 
     */
    public PorCuentadeTerceros.InformacionFiscalTercero createPorCuentadeTercerosInformacionFiscalTercero() {
        return new PorCuentadeTerceros.InformacionFiscalTercero();
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros.InformacionAduanera }
     * 
     */
    public PorCuentadeTerceros.InformacionAduanera createPorCuentadeTercerosInformacionAduanera() {
        return new PorCuentadeTerceros.InformacionAduanera();
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros.Parte }
     * 
     */
    public PorCuentadeTerceros.Parte createPorCuentadeTercerosParte() {
        return new PorCuentadeTerceros.Parte();
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros.CuentaPredial }
     * 
     */
    public PorCuentadeTerceros.CuentaPredial createPorCuentadeTercerosCuentaPredial() {
        return new PorCuentadeTerceros.CuentaPredial();
    }

    /**
     * Create an instance of {@link TeInformacionAduanera32 }
     * 
     */
    public TeInformacionAduanera32 createTeInformacionAduanera32() {
        return new TeInformacionAduanera32();
    }

    /**
     * Create an instance of {@link TeUbicacionFiscal }
     * 
     */
    public TeUbicacionFiscal createTeUbicacionFiscal() {
        return new TeUbicacionFiscal();
    }

    /**
     * Create an instance of {@link TeImporte }
     * 
     */
    public TeImporte createTeImporte() {
        return new TeImporte();
    }

    /**
     * Create an instance of {@link NCURP }
     * 
     */
    public NCURP createNCURP() {
        return new NCURP();
    }

    /**
     * Create an instance of {@link NImporte }
     * 
     */
    public NImporte createNImporte() {
        return new NImporte();
    }

    /**
     * Create an instance of {@link Donatarias }
     * 
     */
    public Donatarias createDonatarias() {
        return new Donatarias();
    }

    /**
     * Create an instance of {@link Divisas }
     * 
     */
    public Divisas createDivisas() {
        return new Divisas();
    }

    /**
     * Create an instance of {@link ImpuestosLocales.RetencionesLocales }
     * 
     */
    public ImpuestosLocales.RetencionesLocales createImpuestosLocalesRetencionesLocales() {
        return new ImpuestosLocales.RetencionesLocales();
    }

    /**
     * Create an instance of {@link ImpuestosLocales.TrasladosLocales }
     * 
     */
    public ImpuestosLocales.TrasladosLocales createImpuestosLocalesTrasladosLocales() {
        return new ImpuestosLocales.TrasladosLocales();
    }

    /**
     * Create an instance of {@link LeyendasFiscales.Leyenda }
     * 
     */
    public LeyendasFiscales.Leyenda createLeyendasFiscalesLeyenda() {
        return new LeyendasFiscales.Leyenda();
    }

    /**
     * Create an instance of {@link PFintegranteCoordinado }
     * 
     */
    public PFintegranteCoordinado createPFintegranteCoordinado() {
        return new PFintegranteCoordinado();
    }

    /**
     * Create an instance of {@link TuristaPasajeroExtranjero.DatosTransito }
     * 
     */
    public TuristaPasajeroExtranjero.DatosTransito createTuristaPasajeroExtranjeroDatosTransito() {
        return new TuristaPasajeroExtranjero.DatosTransito();
    }

    /**
     * Create an instance of {@link CFDIRegistroFiscal }
     * 
     */
    public CFDIRegistroFiscal createCFDIRegistroFiscal() {
        return new CFDIRegistroFiscal();
    }

    /**
     * Create an instance of {@link PrestadoresDeServiciosDeCFDSP }
     * 
     */
    public PrestadoresDeServiciosDeCFDSP createPrestadoresDeServiciosDeCFDSP() {
        return new PrestadoresDeServiciosDeCFDSP();
    }

    /**
     * Create an instance of {@link PrestadoresDeServiciosDeCFD }
     * 
     */
    public PrestadoresDeServiciosDeCFD createPrestadoresDeServiciosDeCFD() {
        return new PrestadoresDeServiciosDeCFD();
    }

    /**
     * Create an instance of {@link ComplementoSPEI.SPEITercero.Ordenante }
     * 
     */
    public ComplementoSPEI.SPEITercero.Ordenante createComplementoSPEISPEITerceroOrdenante() {
        return new ComplementoSPEI.SPEITercero.Ordenante();
    }

    /**
     * Create an instance of {@link ComplementoSPEI.SPEITercero.Beneficiario }
     * 
     */
    public ComplementoSPEI.SPEITercero.Beneficiario createComplementoSPEISPEITerceroBeneficiario() {
        return new ComplementoSPEI.SPEITercero.Beneficiario();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados.Traslado }
     * 
     */
    public EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados.Traslado createEstadoDeCuentaCombustibleConceptosConceptoEstadoDeCuentaCombustibleTrasladosTraslado() {
        return new EstadoDeCuentaCombustible.Conceptos.ConceptoEstadoDeCuentaCombustible.Traslados.Traslado();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaBancario.Movimientos.MovimientoECB }
     * 
     */
    public EstadoDeCuentaBancario.Movimientos.MovimientoECB createEstadoDeCuentaBancarioMovimientosMovimientoECB() {
        return new EstadoDeCuentaBancario.Movimientos.MovimientoECB();
    }

    /**
     * Create an instance of {@link EstadoDeCuentaBancario.Movimientos.MovimientoECBFiscal }
     * 
     */
    public EstadoDeCuentaBancario.Movimientos.MovimientoECBFiscal createEstadoDeCuentaBancarioMovimientosMovimientoECBFiscal() {
        return new EstadoDeCuentaBancario.Movimientos.MovimientoECBFiscal();
    }

    /**
     * Create an instance of {@link Nomina.HorasExtras.HorasExtra }
     * 
     */
    public Nomina.HorasExtras.HorasExtra createNominaHorasExtrasHorasExtra() {
        return new Nomina.HorasExtras.HorasExtra();
    }

    /**
     * Create an instance of {@link Nomina.Incapacidades.Incapacidad }
     * 
     */
    public Nomina.Incapacidades.Incapacidad createNominaIncapacidadesIncapacidad() {
        return new Nomina.Incapacidades.Incapacidad();
    }

    /**
     * Create an instance of {@link Nomina.Deducciones.Deduccion }
     * 
     */
    public Nomina.Deducciones.Deduccion createNominaDeduccionesDeduccion() {
        return new Nomina.Deducciones.Deduccion();
    }

    /**
     * Create an instance of {@link Nomina.Percepciones.Percepcion }
     * 
     */
    public Nomina.Percepciones.Percepcion createNominaPercepcionesPercepcion() {
        return new Nomina.Percepciones.Percepcion();
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros.Impuestos.Traslados.Traslado }
     * 
     */
    public PorCuentadeTerceros.Impuestos.Traslados.Traslado createPorCuentadeTercerosImpuestosTrasladosTraslado() {
        return new PorCuentadeTerceros.Impuestos.Traslados.Traslado();
    }

    /**
     * Create an instance of {@link PorCuentadeTerceros.Impuestos.Retenciones.Retencion }
     * 
     */
    public PorCuentadeTerceros.Impuestos.Retenciones.Retencion createPorCuentadeTercerosImpuestosRetencionesRetencion() {
        return new PorCuentadeTerceros.Impuestos.Retenciones.Retencion();
    }

    /**
     * Create an instance of {@link Comprobante.Impuestos.Traslados.Traslado }
     * 
     */
    public Comprobante.Impuestos.Traslados.Traslado createComprobanteImpuestosTrasladosTraslado() {
        return new Comprobante.Impuestos.Traslados.Traslado();
    }

    /**
     * Create an instance of {@link Comprobante.Impuestos.Retenciones.Retencion }
     * 
     */
    public Comprobante.Impuestos.Retenciones.Retencion createComprobanteImpuestosRetencionesRetencion() {
        return new Comprobante.Impuestos.Retenciones.Retencion();
    }

    /**
     * Create an instance of {@link Comprobante.Conceptos.Concepto.CuentaPredial }
     * 
     */
    public Comprobante.Conceptos.Concepto.CuentaPredial createComprobanteConceptosConceptoCuentaPredial() {
        return new Comprobante.Conceptos.Concepto.CuentaPredial();
    }

    /**
     * Create an instance of {@link Comprobante.Conceptos.Concepto.ComplementoConcepto }
     * 
     */
    public Comprobante.Conceptos.Concepto.ComplementoConcepto createComprobanteConceptosConceptoComplementoConcepto() {
        return new Comprobante.Conceptos.Concepto.ComplementoConcepto();
    }

    /**
     * Create an instance of {@link Comprobante.Conceptos.Concepto.Parte }
     * 
     */
    public Comprobante.Conceptos.Concepto.Parte createComprobanteConceptosConceptoParte() {
        return new Comprobante.Conceptos.Concepto.Parte();
    }

    /**
     * Create an instance of {@link Comprobante.Emisor.RegimenFiscal }
     * 
     */
    public Comprobante.Emisor.RegimenFiscal createComprobanteEmisorRegimenFiscal() {
        return new Comprobante.Emisor.RegimenFiscal();
    }

}
